apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 3.10.0
  interval: 30m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/openebs/charts/blob/main/charts/openebs/values.yaml
  values:
    analytics:
      enabled: false
    localprovisioner:
      hostpathClass:
        isDefaultClass: true
