apiVersion: v1
kind: Service
metadata:
  name: capacitor
  labels:
    app: capacitor
spec:
  selector:
    app: capacitor
  type: NodePort
  ports:
    - port: 9000
      nodePort: 32080
      name: http
